services:
  # ui:
  #   build: 
  #     context: .
  #     dockerfile: ./Dockerfile
  #   image: "locallm-webui"
  #   container_name: "locallm-webui"
  #   ports:
  #     - "3000:3000"
  #   restart: unless-stopped
  #   depends_on:
  #     - postgres
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  postgres:
    hostname: postgres
    build:
      context: .
      dockerfile: ./.local/cluster/postgres.Dockerfile
    image: "llmchat-db"
    container_name: "llmchat_db"
    environment:
      POSTGRES_DB: "llmchat"
      POSTGRES_USER: "locallm"
      POSTGRES_PASSWORD: "locallm"
      PGDATA: "/data/llmchat-db"
    volumes:
       - "llmchat-db-docker:/data/llmchat-db"
    ports:
      - "5431:5432"
    restart: unless-stopped
  # ollama:
  #   volumes:
  #     - ollama:/root/.ollama
  #   container_name: ollama
  #   pull_policy: always
  #   tty: true
  #   restart: unless-stopped
  #   image: ollama/ollama:latest
volumes:
    # ollama: {}
    llmchat-db-docker:
      external: true
